### ISSUE TITLE
12490f rx580 B760i

### ISSUE THREAD

**Issue by JChaooo** [hackintosh-club/JINGYUE-B760I-GAMING-OpenCore#1]
## 你好，请问我这套配置可以直接用你这个EFI嘛？
![image](https://github.com/hackintosh-club/JINGYUE-B760I-GAMING-OpenCore/assets/109884231/04fbf7d3-622d-404b-82ab-d81af1435d13)

**Comment by WuLongMiTaoLaiYiDa** [comment]
> ## 你好，请问我这套配置可以直接用你这个EFI嘛？
> ![image](https://user-images.githubusercontent.com/109884231/257852413-04fbf7d3-622d-404b-82ab-d81af1435d13.png)

https://github.com/hackintosh-club/JINGYUE-B760I-SNOW-DREAM-OpenCore

你的主板EFI看另外一个链接
